-- Add enhanced property details
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "lotSize" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "buildingSize" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "numberOfFloors" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "constructionType" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "heatingSystem" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "coolingSystem" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "amenities" JSONB;

-- Add financial information
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "purchasePrice" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "purchaseDate" TIMESTAMP(3);
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "currentMarketValue" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "annualPropertyTax" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "annualInsurance" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "monthlyHOA" DOUBLE PRECISION;
